# Generated by Django 3.1.3 on 2021-02-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210207_0222'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
