# Generated by Django 3.1.3 on 2021-02-23 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_forum_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='section',
            field=models.CharField(default='General', max_length=12),
        ),
    ]
