# Generated by Django 3.1.3 on 2021-02-23 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_discussions'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Discussions',
        ),
    ]
