# Generated by Django 3.1.3 on 2021-02-23 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_delete_discussions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forum',
            name='section',
            field=models.CharField(max_length=12),
        ),
        migrations.DeleteModel(
            name='section',
        ),
    ]
