# Generated by Django 3.1.3 on 2021-03-01 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_section'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
        migrations.AlterField(
            model_name='forum',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
