# Generated by Django 3.1.3 on 2021-03-01 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_auto_20210301_1425'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
