# Generated by Django 3.1.3 on 2021-03-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_auto_20210301_1543'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='name',
            field=models.CharField(default='anonymous', max_length=200),
        ),
    ]
