# Generated by Django 3.1.3 on 2021-03-09 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_auto_20210301_1728'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
