# Generated by Django 3.1.3 on 2021-03-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_auto_20210309_1708'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='likeScore',
            field=models.IntegerField(default=0),
        ),
    ]
