# Generated by Django 3.1.3 on 2021-03-09 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0020_forum_likescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='forum',
            old_name='likeScore',
            new_name='likeCount',
        ),
        migrations.AddField(
            model_name='forum',
            name='dislikeCount',
            field=models.IntegerField(default=0),
        ),
    ]
