# Generated by Django 3.1.3 on 2021-03-23 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20210309_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='forum',
            field=models.ForeignKey(blank=True, default='General', on_delete=django.db.models.deletion.CASCADE, to='app.forum'),
        ),
    ]
