# Generated by Django 3.1.3 on 2021-04-05 17:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0023_auto_20210405_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='forumLikes',
            field=models.ManyToManyField(related_name='forum', to=settings.AUTH_USER_MODEL),
        ),
    ]
