# Generated by Django 3.1.3 on 2021-04-18 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_auto_20210405_1542'),
    ]

    operations = [
        migrations.AddField(
            model_name='discussion',
            name='isHealth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='discussion',
            name='isTech',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forum',
            name='isHealth',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='forum',
            name='isTech',
            field=models.BooleanField(default=False),
        ),
    ]
