# Generated by Django 3.1.3 on 2021-04-18 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0026_auto_20210418_1757'),
    ]

    operations = [
        migrations.RenameField(
            model_name='discussion',
            old_name='isHealth',
            new_name='UserIsHealthExpert',
        ),
        migrations.RenameField(
            model_name='discussion',
            old_name='isTech',
            new_name='UserIsTechExpert',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='isHealth',
            new_name='UserIsHealthExpert',
        ),
        migrations.RenameField(
            model_name='forum',
            old_name='isTech',
            new_name='UserIsTechExpert',
        ),
    ]
